[workspace]
members = ["featureflag", "featureflag-test", "featureflag-test-macros"]
resolver = "2"

[workspace.package]
edition = "2024"
license = "Apache-2.0"
rust-version = "1.85"

[workspace.lints.rust]
missing_docs = "warn"

[workspace.lints.clippy]
