[package]
name = "featureflag-test"

edition = "2024"
version = "0.0.1"

[dependencies]
featureflag = { version = "0.0.1", path = "../featureflag" }
featureflag-test-macros = { version = "0.0.1", path = "../featureflag-test-macros" }

[lints]
workspace = true
